CONTRACT_ID = platform-ysyxsoc-default-suite
CONTRACT_GROUP = platform-layout
CONTRACT_ARCHS = riscv32e-ysyxsoc
CONTRACT_POINTS = ysyxsoc-address-map ysyxsoc-boot-default ysyxsoc-runtime-copy ysyxsoc-trm-init-order
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
