CONTRACT_ID = core-halt-nonzero
CONTRACT_GROUP = core
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_POINTS = halt-nonzero-bad
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
