name: B阶段考核提交表单
description: 申请B阶段考核
body:
  - type: input
    id: stuid
    attributes:
      label: 一生一芯学号
      description: 填写8位的一生一芯学号
    validations:
      required: true
  - type: input
    id: repo-url
    attributes:
      label: 仓库URL
      description: 填写仓库URL
      placeholder: https://github.com/OSCPU/ysyx-workbench
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: 分支名
      description: 填写分支名
      placeholder: main
    validations:
      required: true
  - type: input
    id: comment
    attributes:
      label: 注释
      description: 填写注释, 可用于标识此次提交
      placeholder: my submission
    validations:
      required: true
  - type: checkboxes
    id: make
    attributes:
      label: make参数
      description: 根据情况选择
      options:
        - label: 不使用'-j'参数, 若cpu-tests等测试由于该参数而失败, 可以勾选此项
          required: false
