exe_addi  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = src1 + imm; goto __instpat_end_;
exe_sw    :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; Mw(src1 + imm, 4, src2); goto __instpat_end_;
exe_bne   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; s->dnpc = (src1 != src2 ? s->pc + imm : s->dnpc); goto __instpat_end_;
exe_lw    :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT(Mr(src1 + imm, 4), 32); goto __instpat_end_;
exe_add   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = src1 + src2; goto __instpat_end_;
exe_slli  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = src1 << SHAMT_LONG; goto __instpat_end_;
exe_beq   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; s->dnpc = (src1 == src2 ? s->pc + imm : s->dnpc); goto __instpat_end_;
exe_bltu  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; s->dnpc = ((word_t)src1 < (word_t)src2 ? s->pc + imm : s->dnpc); goto __instpat_end_;
exe_jalr  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = s->pc + 4; s->dnpc = (src1 + imm) & (~1); goto __instpat_end_;
exe_lhu   :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = Mr(src1 + imm, 2); goto __instpat_end_;
exe_or    :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = src1 | src2; goto __instpat_end_;
exe_jal   :  imm = icache[index].imm;rd = icache[index].rd; R(rd) = s->pc + 4; s->dnpc = s->pc + imm; goto __instpat_end_;
exe_auipc :  imm = icache[index].imm;rd = icache[index].rd; R(rd) = s->pc + imm; goto __instpat_end_;
exe_lui   :  imm = icache[index].imm;rd = icache[index].rd; R(rd) = imm; goto __instpat_end_;
exe_lbu   :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = Mr(src1 + imm, 1); goto __instpat_end_;
exe_lb    :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT(Mr(src1 + imm, 1), 8); goto __instpat_end_;
exe_lh    :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT(Mr(src1 + imm, 2), 16); goto __instpat_end_;
exe_andi  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = src1 & imm; goto __instpat_end_;
exe_addiw :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT(BITS(src1 + imm, 31, 0),32); goto __instpat_end_;
exe_sltiu :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = ((word_t)src1 < (word_t)imm ? 1 : 0); goto __instpat_end_;
exe_slti  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = ((sword_t)src1 < (sword_t)imm ? 1 : 0); goto __instpat_end_;
exe_ld    :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = Mr(src1 + imm, 8); goto __instpat_end_;
exe_xori  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = src1 ^ imm; goto __instpat_end_;
exe_ori   :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = src1 | imm; goto __instpat_end_;
exe_srai  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = (sword_t)src1 >> (sword_t)SHAMT_LONG; goto __instpat_end_;
exe_sraiw :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT((int32_t)src1 >> (int32_t)SHAMT, 32); goto __instpat_end_;
exe_srli  :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = src1 >> SHAMT_LONG; goto __instpat_end_;
exe_sd    :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; Mw(src1 + imm, 8, src2); goto __instpat_end_;
exe_sh    :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; Mw(src1 + imm, 2, src2); goto __instpat_end_;
exe_sb    :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; Mw(src1 + imm, 1, src2); goto __instpat_end_;
exe_blt   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; s->dnpc = ((sword_t)src1 < (sword_t)src2 ? s->pc + imm : s->dnpc); goto __instpat_end_;
exe_bge   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; s->dnpc = ((sword_t)src1 >= (sword_t)src2 ? s->pc + imm : s->dnpc); goto __instpat_end_;
exe_bgeu  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); imm = icache[index].imm;rd = icache[index].rd; s->dnpc = ((word_t)src1 >= (word_t)src2 ? s->pc + imm : s->dnpc); goto __instpat_end_;
exe_addw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT(BITS((uint32_t)src1 + (uint32_t)src2, 31, 0),32); goto __instpat_end_;
exe_sub   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = src1 - src2; goto __instpat_end_;
exe_and   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = src1 & src2; goto __instpat_end_;
exe_xor   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = src1 ^ src2; goto __instpat_end_;
exe_sllw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((uint32_t)src1 << BITS(src2, 4, 0), 32); goto __instpat_end_;
exe_sltu  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = ((word_t)src1 < (word_t)src2 ? 1 : 0); goto __instpat_end_;
exe_slt   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = ((sword_t)src1 < (sword_t)src2 ? 1 : 0); goto __instpat_end_;
exe_sra   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = (sword_t)src1 >> (sword_t)src2; goto __instpat_end_;
exe_srl   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = (word_t)src1 >> (word_t)src2; goto __instpat_end_;
exe_sraw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((int32_t)src1 >> (int32_t)BITS(src2, 4, 0), 32); goto __instpat_end_;
exe_srlw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((uint32_t)src1 >> (uint32_t)BITS(src2, 4, 0), 32); goto __instpat_end_;
exe_sll   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = src1 << BITS(src2, 4, 0); goto __instpat_end_;
exe_mulh  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = BITS((int64_t)(int32_t)src1 * (int64_t)(int32_t)src2, 63,32); goto __instpat_end_;
exe_mulhu :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = BITS((uint64_t)(uint32_t)src1 * (uint64_t)(uint32_t)src2, 63,32); goto __instpat_end_;
exe_mul   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = (sword_t)src1 * (sword_t)src2; goto __instpat_end_;
exe_mulw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT(BITS(src1 * src2, 31, 0), 32); goto __instpat_end_;
exe_rem   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = (sword_t)src1 % (sword_t)src2; goto __instpat_end_;
exe_remu  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = (word_t)src1 % (word_t)src2; goto __instpat_end_;
exe_remw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((int32_t)BITS(src1,31,0)%(int32_t)BITS(src2,31,0) ,32); goto __instpat_end_;
exe_remuv :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((uint32_t)BITS(src1,31,0)%(uint32_t)BITS(src2,31,0) ,32); goto __instpat_end_;
exe_subw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT(BITS(src1 - src2, 31, 0), 32); goto __instpat_end_;
exe_div   :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = ((sword_t)src1 / (sword_t)src2); goto __instpat_end_;
exe_divu  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = ((word_t)src1 / (word_t)src2); goto __instpat_end_;
exe_divw  :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((int32_t)BITS(src1,31,0)/(int32_t)BITS(src2,31,0),  32); goto __instpat_end_;
exe_divuw :  src1 = R(icache[index].rs1); src2 = R(icache[index].rs2); rd = icache[index].rd; R(rd) = SEXT((uint32_t)BITS(src1,31,0)/(uint32_t)BITS(src2,31,0), 32); goto __instpat_end_;
exe_csrrw :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = CSR(imm); CSR(imm) = src1; goto __instpat_end_;
exe_csrrs :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = CSR(imm); CSR(imm) |= src1; goto __instpat_end_;
exe_ecall :  rd = icache[index].rd; ECALL(s->dnpc); goto __instpat_end_;
exe_mret  :  rd = icache[index].rd; MRET(); goto __instpat_end_;
exe_ebreak:  rd = icache[index].rd; NEMUTRAP(s->pc, R(10)); goto __instpat_end_;
exe_inv   :  rd = icache[index].rd; INV(s->pc); goto __instpat_end_;
exe_slliw :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT((uint32_t)src1 << SHAMT, 32); goto __instpat_end_;
exe_srliw :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = SEXT((uint32_t)src1 >> SHAMT, 32); goto __instpat_end_;
exe_lwu   :  src1 = R(icache[index].rs1); imm = icache[index].imm;rd = icache[index].rd; R(rd) = Mr(src1 + imm, 4); goto __instpat_end_;
