#define MIE_SSIE (1 << 1)
#define MIE_MSIE (1 << 3)
#define MIE_STIE (1 << 5)
#define MIE_MTIE (1 << 7)
#define MIE_SEIE (1 << 9)
#define MIE_MEIE (1 << 11)
#define MIE_LCOFIE (1 << 13)

#define MIP_SSIP (1 << 1)
#define MIP_MSIP (1 << 3)
#define MIP_STIP (1 << 5)
#define MIP_MTIP (1 << 7)
#define MIP_SEIP (1 << 9)
#define MIP_MEIP (1 << 11)
#define MIP_LCOFIP (1 << 13)

#define SIP_SSIE (1 << 1)
#define SIP_SSIP (1 << 1)
#define SIP_STIP (1 << 5)
#define SIP_SEIP (1 << 9)
#define SIP_LCOFIP (1 << 13)

#define SIE_SSIE (1 << 1)
#define SIE_STIE (1 << 5)
#define SIE_SEIE (1 << 9)
#define SIE_LCOFIE (1 << 13)

#define SSTATUS_SIE (1 << 1)
#define SSTATUS_SPIE (1 << 5)
#define SSTATUS_UBE (1 << 6)
#define SSTATUS_SPP (1 << 8)
#define SSTATUS_VS (3 << 9)
#define SSTATUS_FS (3 << 13)
#define SSTATUS_SUM (1 << 18)
#define SSTATUS_MXR (1 << 19)
#define SSTATUS_SPELP (1 << 23)
#define SSTATUS_SDT (1 << 24)
