CONTRACT_ID = cte-csr-suite
CONTRACT_GROUP = cte
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_POINTS = csr-preservation
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
