CONTRACT_ID = cte-basic-suite
CONTRACT_GROUP = cte
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_POINTS = init-entry event-dispatch mepc-return interrupt-control
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
