# RTL inventory and the generated CPU bundle.

RTL_OUT := $(ARTIFACT_ROOT)/ysyx_26010028.v
RTL_CORE := $(sort $(wildcard $(NPC_DIR)/vsrc/cpu/*.v))
RTL_TOP_FILE := $(abspath $(NPC_DIR)/vsrc/testbench/npc_top.v)
RTL_HEADER := $(shell find $(NPC_DIR)/vsrc -type f \( -name '*.vh' -o -name '*.svh' \))

SIM_TOP_npc := npc_top
SIM_TOP_ysyxsoc := ysyxSoCFull
SIM_TOP := $(SIM_TOP_$(SIM_MODE))

SIM_RTL_npc := $(RTL_OUT) $(RTL_TOP_FILE)
SIM_RTL_ysyxsoc := $(RTL_OUT) $(sort $(shell find $(YSYX_SOC_HOME)/perip -name '*.v')) $(YSYX_SOC_HOME)/build/ysyxSoCFull.v
SIM_RTL := $(SIM_RTL_$(SIM_MODE))

RTL_INC := $(NPC_DIR)/vsrc $(NPC_DIR)/vsrc/cpu
ifeq ($(SIM_MODE),npc)
  RTL_INC += $(NPC_DIR)/vsrc/testbench
else
  SOC_BIND_FILE := $(MODE_ARTIFACT)/auto_bind.cpp
  NXDC_INPUT := $(NPC_DIR)/constr/ysyxSoCFull.nxdc
  RTL_INC += $(YSYX_SOC_HOME)/perip/uart16550/rtl $(YSYX_SOC_HOME)/perip/spi/rtl
  include $(NVBOARD_HOME)/scripts/nvboard.mk
  HOST_INCLUDES += $(NVBOARD_USR_INC)
  SOC_INPUTS := $(NVBOARD_ARCHIVE)
  SOC_DEPS := $(NVBOARD_ARCHIVE)
  SRCS += $(SOC_BIND_FILE)
endif

$(ARTIFACT_ROOT):
	@mkdir -p $@

$(RTL_OUT): $(RTL_CORE) | $(ARTIFACT_ROOT)
	@printf '[npc][verilog] bundling units=%s output=%s\n' '$(words $(RTL_CORE))' '$@'
	@tmp="$@.tmp"; \
	for unit in $^; do cat "$$unit"; printf '\n'; done > "$$tmp"; \
	mv -f "$$tmp" "$@"
	@printf '[npc][verilog] generated bytes=%s\n' "$$(wc -c < '$@')"

$(SOC_BIND_FILE): $(NXDC_INPUT) | $(MODE_ARTIFACT)
	@printf '[npc][bind] input=%s output=%s\n' '$(NXDC_INPUT)' '$@'
	@mkdir -p $(dir $@)
	@NVBOARD_HOME=$(NVBOARD_HOME) python3 $(NVBOARD_HOME)/scripts/auto_pin_bind.py $^ $@

.PHONY: rtl-bundle
rtl-bundle: $(RTL_OUT)
