# Chisel 生成 verilog 配置
CHISEL_VERILOG_SOC_CONFIG=ICACHE_SIZE_BITS=1
CHISEL_VERILOG_SOC_CONFIG+=ICACHE_BLOCK_BITS=0
CHISEL_VERILOG_SOC_CONFIG+=ICACHE_ENABLE_BURST=false
ifdef CONFIG_TRACE
CHISEL_VERILOG_SOC_CONFIG+=NPC_ENABLE_DEBUG=true
else 
CHISEL_VERILOG_SOC_CONFIG+=NPC_ENABLE_DEBUG=false
endif
verilog-soc: 
	@echo CHISEL_VERILOG_SOC_CONFIG $(CHISEL_VERILOG_SOC_CONFIG)
	$(MAKE) -C ../npc-chisel $(CHISEL_VERILOG_SOC_CONFIG) verilog
