# Chisel 生成 verilog 配置
CHISEL_VERILOG_CONFIG=ICACHE_SIZE_BITS=1
CHISEL_VERILOG_CONFIG+=ICACHE_BLOCK_BITS=0
CHISEL_VERILOG_CONFIG+=ICACHE_ENABLE_BURST=false
CHISEL_VERILOG_CONFIG+=ENABLE_SOC=false
CHISEL_VERILOG_CONFIG+=BURST_LENGTH=0
CHISEL_VERILOG_CONFIG+=NPC_ENABLE_DEBUG=false

verilog-npc: 
	@echo CHISEL_VERILOG_CONFIG $(CHISEL_VERILOG_CONFIG) 
	$(MAKE) -C ../npc-chisel $(CHISEL_VERILOG_CONFIG) verilog-npc
