CONTRACT_ID = preflight-run-command
CONTRACT_GROUP = preflight
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_POINTS = run-command
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
