CONTRACT_ID = klib-suite
CONTRACT_GROUP = klib
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_POINTS = string-api stdio-format-buffer stdio-printf-output int64-runtime-rv32e stdlib-api
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
