CONTRACT_ID = ioe-suite
CONTRACT_GROUP = ioe-auto
CONTRACT_ARCHS = riscv32-nemu riscv32e-npc riscv32e-ysyxsoc
CONTRACT_POINTS = dispatch-config timer-uptime-precision timer-rtc uart-loop input-idle-auto gpu-auto-smoke gpio-auto-smoke
CONTRACT_ROOT = ../..
SRCS = src/main.c
include $(CONTRACT_ROOT)/contract.mk
