version = 3.7.15
runner.dialect = scala213

maxColumn = 200
align.preset = most
indent.defnSite = 2
assumeStandardLibraryStripMargin = true
align.stripMargin = false
docstrings.style = SpaceAsterisk
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true

align.tokens."+" = [ {
    code = ":"
    }]

    newlines.beforeCurlyLambdaParams = "never"
    newlines.alwaysBeforeMultilineDef = false
    newlines.implicitParamListModifierForce = [before]

    verticalMultiline.atDefnSite = true

    optIn.annotationNewlines = true

rewrite.rules = [SortImports, PreferCurlyFors, AvoidInfix]
fileOverride {
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
}
