version = "3.10.4"
runner.dialect = scala213

maxColumn = 100
align.preset = some
indent.defnSite = 2
assumeStandardLibraryStripMargin = true
align.stripMargin = true
docstrings.style = SpaceAsterisk
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true

align.tokens."+" = [{
code = ":"
}]

newlines.beforeCurlyLambdaParams = "never"
newlines.alwaysBeforeMultilineDef = false
newlines.implicitParamListModifierForce = [before]

verticalMultiline.atDefnSite = true

optIn.annotationNewlines = true

rewrite.rules = [SortImports, PreferCurlyFors, AvoidInfix]
fileOverride {
  "glob:**/.bsp/out/mill-build/generatedScriptSources.dest/support/**" {
     runner.dialect = scala3
  }
  "glob:**/build.mill/**" {
     runner.dialect = scala3
  }
}
