CXXFLAGS += -std=c++20
CXXFLAGS += -g -O0
CXXFLAGS += $(addprefix -I,$(shell find src/cpp -type d))
CXXFLAGS += -DVERILATOR=1 -DVM_TRACE=1 -DVM_TRACE_VCD=1
CXXFLAGS += -DTOP_HEADER="\"V$(TOP).h\"" -DVTop=V$(TOP) -DTOP_PROOT_HEADER="\"V$(TOP)___024root.h\""
CXXFLAGS += -DLITTLE_ENDIAN_PLATFORM
CXXFLAGS += -DNPC_RESET_VECTOR=$(NPC_RESET_VECTOR)u
INC_PATH += $(VERILATOR_DIR)
INC_PATH += $(VERILATOR_ROOT)/include
INC_PATH += $(VERILATOR_ROOT)/include/vltstd
INCFLAGS = $(addprefix -I, $(INC_PATH))
CXXFLAGS += $(INCFLAGS)
LDFLAGS += -lreadline
