name: Test Workflow

on:
  push:
    branches:
      - ysyx-submit

permissions:
  contents: write      # For checkout and reading commit info
  pull-requests: write # For merging and commenting on PRs

jobs:
  hello:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: hello
        run: $MAKE ARCH=riscv32e-npc -C $YSYX_HOME/am-kernels/kernels/hello run

  cpu-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Prepare
        uses: ./.github/actions/prepare
      - name: cpu-tests
        run: $MAKE ARCH=riscv32e-npc -C $YSYX_HOME/am-kernels/tests/cpu-tests run
