# .github/workflows/auto_validate_merge_pr.yml
name: Auto Validate (Git Commit Author) and Merge Student PR

on:
  push:
    branches:
      - ysyx-submit

permissions:
  contents: write      # For checkout and reading commit info
  pull-requests: write # For merging and commenting on PRs

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Check submit flag
        run: |
          MSG=$(git log -1)
          SUBMIT_FLAG=$(echo $MSG | grep -o "YSYX_SUBMIT=true")
          if [[ $SUBMIT_FLAG == "" ]]; then
            echo "Missing flag 'YSYX_SUBMIT=true' in the commit message. Abort."
            false
          fi

      - name: Get student ID
        id: get-stuid
        run: |
          STUID=$(grep -E -o "STUID = ysyx_[0-9]{8}" Makefile)
          if [[ $STUID == "" ]]; then
            echo "Missing STUID in Makefile (format: STUID = ysyx_XXXXXXXX). Abort."
            false
          fi
          STUID=$(echo $STUID | grep -E -o "[0-9]{8}$")
          echo "STUID=$STUID" >> $GITHUB_ENV

      - name: Check student ID in whitelist
        run: |
          wget https://raw.githubusercontent.com/OSCPU/ysyx-workbench/whitelist/whitelist.txt
          if ! grep -o $STUID whitelist.txt 2> /dev/null ; then
            echo "$STUID is not in whitelist. Abort."
            false
          fi

      - name: Setting environment variables
        run: |
          echo "NEMU_HOME=`pwd`/nemu" >> "$GITHUB_ENV"
          echo "AM_HOME=`pwd`/abstract-machine" >> "$GITHUB_ENV"
          echo "NAVY_HOME=`pwd`/navy-apps" >> "$GITHUB_ENV"
          echo "NPC_HOME=`pwd`/npc" >> "$GITHUB_ENV"
          MAKE_CMD="make -j `nproc`"
          echo "MAKE=$MAKE_CMD" >> "$GITHUB_ENV"

      - name: Disable git tracer
        run: |
          echo ".git_commit:" >> Makefile
          echo -e "\t@echo git tracer is disabled" >> Makefile

      - name: Clone repos
        run: |
          git clone https://github.com/NJU-ProjectN/am-kernels

      - name: Install dependency
        run: |
          sudo apt install g++-riscv64-linux-gnu
          sudo sed -i -e '8d' /usr/riscv64-linux-gnu/include/gnu/stubs.h

          mkdir -p ~/.local/bin
          MILL_VERSION=0.11.13
          if [[ -e $NPC_HOME/.mill-version ]]; then
            MILL_VERSION=`cat $NPC_HOME/.mill-version`
          fi
          echo "Downloading mill with version $MILL_VERSION"
          sh -c "curl -L https://github.com/com-lihaoyi/mill/releases/download/$MILL_VERSION/$MILL_VERSION > ~/.local/bin/mill && chmod +x ~/.local/bin/mill"
          mill --version

          wget -q https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2025-04-24/oss-cad-suite-linux-x64-20250424.tgz
          tar xf oss-cad-suite-linux-x64-20250424.tgz
          OSS_CAD_SUITE_BIN_PATH=`pwd`/oss-cad-suite/bin
          echo "PATH=$PATH:$OSS_CAD_SUITE_BIN_PATH" >> "$GITHUB_ENV"

      - name: clean up
        run: |
          $MAKE -C $NEMU_HOME clean
          $MAKE -C $AM_HOME clean-all
          $MAKE -C $NPC_HOME clean

      - name: hello
        run: $MAKE ARCH=riscv32e-npc -C am-kernels/kernels/hello run
      - name: cpu-tests
        run: $MAKE ARCH=riscv32e-npc -C am-kernels/tests/cpu-tests run
